---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opt-splunk-var
  namespace: splunk
spec:
  storageClassName: cephrbd-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opt-splunk-etc
  namespace: splunk
spec:
  storageClassName: cephrbd-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

